name: WebGL Build and Deploy

on:
  push:
    branches: develop
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run the unity build steps
    runs-on: self-hosted

    steps:
      # Actionsがリポジトリにアクセスできるようにする
      - name: Checkout
        uses: actions/checkout@v5

      # Install NuGetForUnity.Cli
      - name: Restore dotnet tool - NuGetForUnity.Cli
        run: dotnet new tool-manifest

      - name: Install NuGetForUnity.Cli Tool
        run: dotnet tool install NuGetForUnity.Cli --version 4.1.1

      - name: Restore NuGet packages using NuGetForUnity.Cli
        run: dotnet nugetforunity restore .

      # LibraryをCacheしてBuildを高速化する
      - uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-PackingGame-Web
          restore-keys: |
            Library-PackingGame-
            Library-

      # WebGLBuildする
      - name: Run WebGL build
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: .
          unityVersion: 6000.0.26f1
          runAsHostUser: true
          allowDirtyBuild: true

      # Build成果物をアップロードする
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL/WebGL
          retention-days: 7 # 念のため

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL/WebGL

      # デプロイする
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: shirurona/PackingGame_dev
          publish_branch: main
          publish_dir: build/WebGL/WebGL