name: Generate issue

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read
  actions: read

jobs:
  generate-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: shirurona/auto-generate-issue # Actionがあるリポジトリ
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: .github/actions/auto-generate-issue
          
      - name: Generate issue
        uses: ./.github/actions/auto-generate-issue
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gemini-token: ${{ secrets.GEMINI_TOKEN }}
          template-filename: issue.md
          project-context: ./CLAUDE.md
