name: Test
  
on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

# 連続して実行されたときに一つ前の実行中のジョブが停止されるようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  unity-Test:
    name: Run the unity test steps
    runs-on: self-hosted
    steps:
      # Actionsがリポジトリにアクセスできるようにする
      - name: Checkout
        uses: actions/checkout@v5

      # Install NuGetForUnity.Cli
      - name: Restore dotnet tool - NuGetForUnity.Cli
        run: dotnet new tool-manifest

      - name: Install NuGetForUnity.Cli Tool
        run: dotnet tool install NuGetForUnity.Cli --version 4.1.1

      - name: Restore NuGet packages using NuGetForUnity.Cli
        run: dotnet nugetforunity restore .
      
      # LibraryをCacheしてBuildを高速化する
      - uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-PackingGame-Web
          restore-keys: |
            Library-PackingGame-
            Library-

      # Testする
      - name: Run the Test
        uses: game-ci/unity-test-runner@v4.3.1
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 6000.0.26f1
          testMode: editmode

          githubToken: ${{ secrets.GITHUB_TOKEN }}



